name: build-openlane-sky130
on: [push]

jobs:
  build-blake2s:
    runs-on: ubuntu-latest
    env:
      REPO : blake2s
      VLNV : secworks:crypto:blake2s
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: blake2s
      - name: Checkout pdk
        uses: actions/checkout@v2
        with:
          repository: olofk/pdklite
          path: pdklite
      - run: echo "PDK_ROOT=$GITHUB_WORKSPACE/pdklite" >> $GITHUB_ENV
      - run: echo "EDALIZE_LAUNCHER=${GITHUB_WORKSPACE}/$REPO/.github/workflows/openlane_runner.py" >> $GITHUB_ENV
      - run: pip3 install --user -e "git+https://github.com/olofk/edalize.git#egg=edalize"
      - run: pip3 install fusesoc
#      - run: docker pull efabless/openlane:v0.12
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130 $VLNV

  sim-icarus:
    runs-on: ubuntu-latest
    env:
      REPO : blake2s
      VLNV : secworks:crypto:blake2s
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: blake2s
      - run: sudo apt install iverilog
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=tb_blake2s_core $VLNV
      - run: fusesoc run --target=tb_blake2s $VLNV

  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : blake2s
      VLNV : secworks:crypto:blake2s
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: blake2s
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV
